// Generated by CoffeeScript 1.12.7
var g_resources, i, j, len, res;

res = {
  HelloWorld_png: "res/HelloWorld.png",
  fragmentWather: "res/shader/fragmentWather.fsh",
  vertex: "res/shader/vertex.vsh"
};

g_resources = [];

for (j = 0, len = res.length; j < len; j++) {
  i = res[j];
  g_resources.push(res[i]);
}
